### ISSUE TITLE
open source this

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/couch-migrations#1]
we agreed with @emig to import code here without keeping the original history. so there will be no problem in keeping this public

**Comment by danse** [comment]
opened

**Comment by emig** [comment]
@danse maybe `eh-couchdb-migrations` ? to scope it to `eh` mig

**Comment by jo** [comment]
:+1: or `eha-couchdb-migrations`

**Comment by jo** [comment]
I just moaned because now is the best time for renaming ;)

**Comment by danse** [comment]
fair enough. this is not going to be a tool, just a collection of our code from where we *might* extract a tool some day, so making it company specific is a good idea

**Comment by danse** [comment]
renamed
